// Generated by Supabase CLI - do not edit
export type Json = string | number | boolean | null | { [key: string]: Json } | Json[]

export interface Database {
  public: {
    Tables: {
      voicemails: {
        Row: {
          id: string
          user_id: string
          audio_url: string
          transcription: string | null
          created_at: string
          sender: string | null
        }
        Insert: {
          id?: string
          user_id: string
          audio_url: string
          transcription?: string | null
          created_at?: string
          sender?: string | null
        }
        Update: {
          id?: string
          user_id?: string
          audio_url?: string
          transcription?: string | null
          created_at?: string
          sender?: string | null
        }
      }
    }
  }
}

